### PR TITLE
[Diggy] Restoring buffs every 61 ticks

### LINKED ISSUE #673: Diggy Level up buffs vanish.
**Describe the bug**
*Note, Single player*
Buffs from leveling up the market (Health, Bonus inventory slots and mining speed bonus) will vanish.

**Expected behavior**
Buffs will persist or be refreshed or re-added if lost.

**Steps to reproduce**
1. Start Diggy in single player
2. Any point after leveling up, save & exit.
3. Add or remove [a] mod[s] (As far as I can tell ANY mod change will trigger this)
4. When save is reloaded, buffs will be absent.

*Edit, removing mods doesn't all ways seem to make the buffs vanish. All test with adding mods did make the buffs vanish.*

**Screenshots**

**Map**
Which map you were playing/which server you were playing on when you found the bug.
Single player Diggy scenario.

**Additional context**

### PR DESCRIPTION
**Pull request by SimonFlapse**
Suggested solution for #673 

Updates all diggy buffs every 61 ticks. If they have been set to zero, restore the values to the active_modifier value.

This only fixes issues caused by mods changing the force modifiers to zero. 

Closes #673

### CODE REVIEW

**Comment by linaori** [comment]
Have you had the chance to test this with a mod?

**Comment by SimonFlapse** [comment]
> Have you had the chance to test this with a mod?

Not really, I don't know what else we should do about it since it seems the mods are messing about with the modifiers. However with this players can set the buffs to 0 and it'll revert back to the correct value.

File: map_gen/Diggy/Feature/Experience.lua [hunk 1]
```diff
@@ -507,6 +508,12 @@ local function update_gui()
             toggle(data)
         end
     end
+
+    --Resets buffs if they have been set to 0
+    local force = players[#players].force
```
Comment (linaori) [inline map_gen/Diggy/Feature/Experience.lua]: What about `game.players.force`? Seems less error-prone

Comment (grilledham) [reply map_gen/Diggy/Feature/Experience.lua]: do you mean `game.forces.player`?

Comment (linaori) [reply map_gen/Diggy/Feature/Experience.lua]: No, `players.game.force`

**Comment by mheguy** [comment]
Rebasing + force pushing to get up to date with the lint-free dev head.

**Comment by SimonFlapse** [comment]
Is this still something we'd be interested in adding to diggy? Or are we looking for another solution/no solution.

File: map_gen/Diggy/Feature/Experience.lua [hunk 2]
```diff
@@ -518,6 +519,12 @@ local function update_gui()
             toggle(data)
         end
     end
+
+    --Resets buffs if they have been set to 0
+    local force = game.forces.player
+    Experience.update_inventory_slots(force, 0)
+    Experience.update_mining_speed(force, 0)
+    Experience.update_health_bonus(force, 0)
```
Comment (mheguy) [inline map_gen/Diggy/Feature/Experience.lua]: Assuming another mod is constantly trying to reset the values to 0, wouldn't that just create a weird situation where a player's health is constantly fluctuating? Or worse, their inventory.

File: map_gen/Diggy/Feature/Experience.lua [hunk 3]
```diff
@@ -117,8 +117,7 @@ function Experience.update_mining_speed(force, level_up)
         mining_efficiency.level_modifier = mining_efficiency.level_modifier + (value * 0.01)
     end
     -- remove the current buff
-    local old_modifier = force.manual_mining_speed_modifier - mining_efficiency.active_modifier
-
+    local old_modifier = (force.manual_mining_speed_modifier == 0) and 0 or force.manual_mining_speed_modifier - mining_efficiency.active_modifier
```
Comment (mheguy) [inline map_gen/Diggy/Feature/Experience.lua]: Rather than only accounting for a force.modifier of 0, this should put a floor of 0 on `force.manual_mining_speed_modifier - mining_efficiency.active_modifier` to prevent a situation where a mod sets a number `> 0` but `< active_modifier` (as this would result in a net buff less than the amount we aimed to give).

**Review by mheguy — CHANGES_REQUESTED** [review]
I'm not sure how to handle the situation as a whole, but we can at least prevent diggy from inflicting a debuff on its players. Edit: my mistake that we wouldn't be creating a debuff, we would just be giving less than the total buff that we should be applying.

File: map_gen/Diggy/Feature/Experience.lua (hunk 3 above)
Comment (SimonFlapse) [reply map_gen/Diggy/Feature/Experience.lua]: Sounds fair. `force.manual_mining_speed_modifier - mining_efficiency.active_modifier` should never be < 0. I think that's everything we can do/should want to do about this issue.

File: map_gen/Diggy/Feature/Experience.lua (hunk 2 above)
Comment (SimonFlapse) [reply map_gen/Diggy/Feature/Experience.lua]: Sounds fair. `force.manual_mining_speed_modifier - mining_efficiency.active_modifier` should never be < 0. I think that's everything we can do/should want to do about this issue.

File: map_gen/Diggy/Feature/Experience.lua (hunk 3 above)
Comment (SimonFlapse) [reply map_gen/Diggy/Feature/Experience.lua]: Sounds fair. `force.manual_mining_speed_modifier - mining_efficiency.active_modifier` should never be < 0. I think that's everything we can do/should want to do about this issue.

File: map_gen/Diggy/Feature/Experience.lua (hunk 2 above)
Comment (SimonFlapse) [reply map_gen/Diggy/Feature/Experience.lua]: That seems like the wrong way to do it. Diggys buffs simply would not be compatible with the mod then. We can't, and should not put too much effort into making this compatible with mods.

**Comment by mheguy** [comment]
On phone so evaluating is a bit difficult but:
It seems the incorrect style is being applied in regards to this line of the style guide:
No spaces after (, [, { or before ], ), }.

In addition, I think force.modifier == 0 and 0 is redundant now that you are instituting a floor of 0.

File: map_gen/maps/diggy/feature/experience.lua [hunk 4]
```diff
@@ -139,13 +139,13 @@ function Experience.update_mining_speed(force, level_up)
...
             local level = get_force_data(force).current_level
-            local adjusted_value = floor(max(buff.value, 24*0.9^level))
+            local adjusted_value = floor(max(buff.value, 24 * 0.9 ^ level))
             local value = (buff.double_level ~= nil and level_up % buff.double_level == 0) and adjusted_value * 2 or adjusted_value
             mining_efficiency.level_modifier = mining_efficiency.level_modifier + (value * 0.01)
         end
         -- remove the current buff
-        local old_modifier = force.manual_mining_speed_modifier - mining_efficiency.active_modifier
-
+        local old_modifier = (force.manual_mining_speed_modifier == 0) and 0 or force.manual_mining_speed_modifier - mining_efficiency.active_modifier
```
Comment (mheguy) [inline map_gen/maps/diggy/feature/experience.lua]: Pretty sure `(force.manual_mining_speed_modifier == 0) and 0 or ` is redundant since we're covering all cases where `force.manual_mining_speed_modifier < mining_efficiency.active_modifier`

File: map_gen/maps/diggy/feature/experience.lua [hunk 5]
```diff
@@ -538,6 +538,12 @@ local function update_gui()
             toggle(data)
         end
     end
+
+    --Resets buffs if they have been set to 0
+    local force = game.forces.player
+    Experience.update_inventory_slots(force, 0)
```
Comment (mheguy) [inline map_gen/maps/diggy/feature/experience.lua:544]: As discussed, "fighting" other mods for control every second might make for a worse player experience

Comment (SimonFlapse) [reply map_gen/maps/diggy/feature/experience.lua:544]: That should only happen if the mod keeps setting the modifier to 0. And if it does we are not at fault. People must understand that adding mods can cause incompatible and inconsistency. I still don't think there is anything else we can do. So either we go with these changes or we just close the PR and not do anything.

Comment (mheguy) [reply map_gen/maps/diggy/feature/experience.lua:544]: I don't think we should add behaviour to combat other mods directly as we don't know if we will make things better or worse, but I think clamping the value of `old_modifier` to not be negative is a very worthwhile change.

Comment (SimonFlapse) [reply map_gen/maps/diggy/feature/experience.lua:544]: Agree, that's a good find :) But we'd not have a solution for #673 and it would keep being brought up

Comment (mheguy) [reply map_gen/maps/diggy/feature/experience.lua:544]: We can't control what other mods do. All we can do is try to be compatible with others, we can't force them to be compatible with others.

File: map_gen/maps/diggy/feature/experience.lua (hunk 4 above)
Comment (mheguy) [reply map_gen/maps/diggy/feature/experience.lua]:
```suggestion
        local old_modifier = force.manual_mining_speed_modifier - mining_efficiency.active_modifier
```

Comment (mheguy) [reply map_gen/maps/diggy/feature/experience.lua]: The suggestion thing is neat

File: map_gen/maps/diggy/feature/experience.lua [hunk 6]
```diff
@@ -167,8 +167,8 @@ function Experience.update_inventory_slots(force, level_up)
         end
 
         -- remove the current buff
-        local old_modifier = force.character_inventory_slots_bonus - inventory_slots.active_modifier
-
+        local old_modifier = (force.character_inventory_slots_bonus == 0) and 0 or force.character_inventory_slots_bonus - inventory_slots.active_modifier
```
Comment (mheguy) [inline map_gen/maps/diggy/feature/experience.lua]:
```suggestion
        local old_modifier = force.character_inventory_slots_bonus - inventory_slots.active_modifier
```

File: map_gen/maps/diggy/feature/experience.lua [hunk 7]
```diff
@@ -185,13 +185,13 @@ function Experience.update_health_bonus(force, level_up)
...
         if level_up > 0 and buff ~= nil then
-            local value = (buff.double_level ~= nil and level_up%buff.double_level == 0) and buff.value*2 or buff.value
+            local value = (buff.double_level ~= nil and level_up % buff.double_level == 0) and buff.value * 2 or buff.value
             health_bonus.level_modifier = health_bonus.level_modifier + value
         end
 
         -- remove the current buff
-        local old_modifier = force.character_health_bonus - health_bonus.active_modifier
-
+        local old_modifier = (force.character_health_bonus == 0) and 0 or force.character_health_bonus - health_bonus.active_modifier
```
Comment (mheguy) [inline map_gen/maps/diggy/feature/experience.lua]:
```suggestion
        local old_modifier = force.character_health_bonus - health_bonus.active_modifier
```

File: map_gen/maps/diggy/feature/experience.lua [hunk 8]
```diff
@@ -269,6 +268,7 @@ local function on_research_finished(event)
 
     Experience.update_inventory_slots(force, 0)
     Experience.update_mining_speed(force, 0)
+    Experience.update_health_bonus(force, 0)
```
Comment (mheguy) [inline map_gen/maps/diggy/feature/experience.lua:271]: Why is this new? Was there a reason health bonus wasn't handled here?

Comment (SimonFlapse) [reply map_gen/maps/diggy/feature/experience.lua:271]: It wasn't needed, since no research added extra health. I've added it for consistency, and it ensures that all the buffs are force updated on a new research as well as every 61 ticks

File: map_gen/maps/diggy/feature/experience.lua (hunk 7 above)
Comment (SimonFlapse) [reply map_gen/maps/diggy/feature/experience.lua]: Yeah that'll work now since we are preventing the ´old_modifier´ from going below 0

**Review by mheguy — APPROVED** [review]
